# Playbook which ramps up myapp tutorial site inside a Vagrant virtual machine

- hosts: all
  gather_facts: true

  # These need to be set up before reading default.yml - more variables are generated based on these
  vars:
    - firewall: on
    - deploy_location: /srv/django/tatianastore
    - package_name: tatianastore
    - site_id: tatianastore
    - site_mode: production
    - smtp: on
    - ssl: off
    - cloudflare: on
    - letsenrypt: off
    - backup: off
    - notify_email: mikko@libertymusicstore.net
    - server_email: no-reply@libertymusicstore.net
    - git_repository: git@github.com:miohtama/LibertyMusicStore.git
    - git_branch: master
    - server_name: libertymusicstore.net
    - server_email_domain: libertymusicstore.net
    - postfix_domain: libertymusicstore.net
    - db_name: tatianastore_production
    - db_user: wsgi
    - db_password: wsgi
    - postgresql_databases:
        - name: "{{ db_name }}"
          hstore: yes
          uuid_ossp: yes
          gis: no
        - name: cryptoassets_production
          hstore: yes
          uuid_ossp: yes
    - motd_template: tatianastore.txt
    # Python versions to install on the server.
    - python_versions: [3.4]
    # We are now stuck with this because http://stackoverflow.com/q/34827566/315168
    - python_interpreter: python3.4

  # Get SMTP settings, etc.
  pre_tasks:
    - include_vars: default.yml  # Populate variables for external roles
    - include_vars: secrets.yml  # Read our secret variables

  roles:
  - { role: websauna.preflight, tags: ['site'] }
  - websauna.users
  - { role: websauna.ssh, tags: ['site'] }  # Needed to setup SSH auth socket for github/bitbucket
  - websauna.shell
  - websauna.harden
  - websauna.smtp
  - { role: ANXS.postgresql, become: yes, become_user: root, tags: ['psql'] }
  - { role: Stouts.nginx, become: yes, become_user: root, tags: ['site'] }  # websauna.site may override Nginx config
  - { role: Stouts.redis, become: yes, become_user: root }
  - { role: Stouts.python, become: yes, become_user: root }
  - { role: libertymusicstore, tags: ['site'] }
  - websauna.postflight


